Local CMS backup
ABI-Software/12-labours-app pull request #84
Opened 2023-09-21 22:44 UTC by ddjnw1yu

Temporary solution for the issue(https://github.com/ABI-Software/12-labours-app/issues/82)
Using local content if don't pass the csm environment variable.
Currently, it will still require for manually running the script to pull the latest cms content before deployment/build docker image.

2023-10-03 20:30 UTC, alan-wu commented on plugins/graphcms.js
> +    graphcms_endpoint ? new GraphQLClient(graphcms_endpoint) : graphcms_endpoint
Clearer when explicitly assign the variabler as `graphcms_endpoint ? new GraphQLClient(graphcms_endpoint) : undefined`.

2023-10-03 20:33 UTC, alan-wu requested changes
Looks good, please see comment for a single line change please.

2023-10-03 20:40 UTC, ddjnw1yu commented
> Looks good, please see comment for a single line change please.

`Undefined` is not available here. I have updated the if statement in **_graphcmsQuery.js_**, that probably will be a better way.

2023-10-04 01:49 UTC, alan-wu approved these changes
Looks good, thanks.

2023-10-04 01:49 UTC, merged